# Generated by Django 3.2.15 on 2022-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Birthday',
            field=models.CharField(max_length=255),
        ),
    ]
